import React,{useState} from "react";
import type { EngineerProfile } from "../../types";
import { ArrowLeft,CreditCard } from "../../components/Icons";
import apiService from "../../services/apiService";

const plans=[{id:'professional',name:'Professional',price:'£7'},{id:'skills',name:'Skills',price:'£15'},{id:'business',name:'Business',price:'£35'}] as const;

export const PaymentsView=({profile,setActiveView}:{profile:EngineerProfile;setActiveView:(view:string)=>void})=>{
 const [issuing,setIssuing]=useState(''),[invoice,setInvoice]=useState<any>(null),[error,setError]=useState('');
 async function issue(plan:typeof plans[number]['id']){setIssuing(plan);setError('');try{const result=await apiService.createMembershipCheckout(plan);setInvoice(result.invoice);window.location.assign(result.checkoutUrl);}catch(error:any){setError(error.message||'Could not start secure membership checkout.');}finally{setIssuing('');}}
 return <div><button onClick={()=>setActiveView("Dashboard")} className="mb-4 flex items-center rounded-md bg-gray-200 px-4 py-2"><ArrowLeft size={16} className="mr-2"/>Back to Dashboard</button><h1 className="mb-4 text-3xl font-bold">Membership billing</h1><div className="rounded-lg bg-white p-6 shadow"><h2 className="mb-4 flex items-center text-xl font-bold"><CreditCard className="mr-3 text-blue-600"/>TechSubbies membership</h2><div className="rounded-lg border border-blue-200 bg-blue-50 p-4"><p className="text-sm font-semibold text-blue-700">Current membership</p><p className="text-2xl font-bold text-blue-900">{profile.profileTier||'Basic'} Plan</p></div><p className="mt-5 text-sm text-gray-700">Choose a paid engineer membership and continue to secure checkout. The membership activates only after TechSubbies receives a verified payment event.</p><div className="mt-5 grid gap-3 md:grid-cols-3">{plans.map(plan=><button key={plan.id} onClick={()=>issue(plan.id)} disabled={Boolean(issuing)} className="rounded-lg border p-4 text-left hover:border-blue-500 disabled:opacity-60"><strong>{plan.name}</strong><div className="mt-1 text-2xl font-bold">{plan.price}<span className="text-sm font-normal"> / month</span></div><div className="mt-3 text-sm text-blue-700">{issuing===plan.id?'Opening checkout…':'Continue to secure checkout'}</div></button>)}</div>{error&&<p className="mt-4 rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}{invoice&&<div className="mt-4 rounded border border-green-200 bg-green-50 p-4 text-sm text-green-900"><strong>Membership checkout created.</strong><div className="mt-1">{invoice.id} · {new Intl.NumberFormat('en-GB',{style:'currency',currency:invoice.currency}).format(invoice.amountPence/100)} · {invoice.status}</div></div>}<p className="mt-5 rounded-lg bg-gray-50 p-4 text-sm text-gray-700">This area covers membership only. TechSubbies does not collect job funds, generate assignment invoices, hold escrow or pay engineers.</p></div></div>;
};
