import React,{useEffect,useMemo,useState} from "react";
import apiService from "../services/apiService";
import { roleSkillTaxonomy } from "../data/roleSkillTaxonomy";
import { analyseTeamCoverage } from "../services/trustEngine";
import type { User } from "../types";
import { canonicalRoleIdsFromProfile } from "../services/canonicalCapability";
import type { ProjectTeamMemberDTO } from "../types/marketplaceApi";
import { errorMessage } from "../utils/errorMessage";

export default function TeamAssemblyPage(){
 const [engineers,setEngineers]=useState<User[]>([]),[name,setName]=useState(""),[required,setRequired]=useState<string[]>([]),[selected,setSelected]=useState<string[]>([]),[status,setStatus]=useState("");
 useEffect(()=>{apiService.listEngineers().then(setEngineers);},[]);
 const members=useMemo<ProjectTeamMemberDTO[]>(()=>selected.map(id=>{const engineer=engineers.find(item=>item.id===id);return{engineerId:id,roleIds:canonicalRoleIdsFromProfile(engineer?.profile)};}),[selected,engineers]);
 const coverage=analyseTeamCoverage(required,members);
 function toggle(list:string[],value:string,setter:(value:string[])=>void){setter(list.includes(value)?list.filter(item=>item!==value):[...list,value]);}
 async function save(){setStatus("Saving…");try{await apiService.createProjectTeam({name:name.trim(),requiredRoleIds:required,members});setStatus("Project team saved to your company workspace.");}catch(error:unknown){setStatus(errorMessage(error,"Project team could not be saved."));}}
 return <main className="min-h-screen bg-slate-950 px-5 py-8 text-white"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">Multi-role resourcing</p><h1 className="mt-2 text-3xl font-bold">Project team assembly</h1><p className="mt-2 max-w-3xl text-slate-400">Define the actual specialist roles required. Related experience does not silently replace a missing lead, commissioning, audio, video, controls or network role.</p></div><a href="/company/talent-pool" className="h-fit rounded-xl border border-white/15 px-4 py-2 font-bold">Talent pool</a></div>
 <label className="mt-7 block max-w-xl text-sm font-bold">Team or project name<input value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full rounded-xl border border-white/15 bg-slate-900 p-3"/></label>
 <section className="mt-6 rounded-2xl border border-white/10 bg-slate-900 p-5"><h2 className="font-bold text-cyan-200">1. Required specialist roles</h2><div className="mt-4 grid max-h-72 gap-2 overflow-auto md:grid-cols-3">{roleSkillTaxonomy.map(role=><button key={role.id} onClick={()=>toggle(required,role.id,setRequired)} className={`rounded-xl border p-3 text-left text-sm ${required.includes(role.id)?"border-cyan-300 bg-cyan-300/15":"border-white/10"}`}><strong>{role.title}</strong><div className="mt-1 text-xs capitalize text-slate-400">{role.market} · {role.family} · {role.level}</div></button>)}</div></section>
 <section className="mt-5 rounded-2xl border border-white/10 bg-slate-900 p-5"><h2 className="font-bold text-cyan-200">2. Select engineers</h2>{engineers.length===0?<p className="mt-3 text-slate-400">No registered engineer profiles are currently available.</p>:<div className="mt-4 grid gap-3 md:grid-cols-2">{engineers.map(engineer=>{const roleIds=canonicalRoleIdsFromProfile(engineer.profile);const covered=required.filter(role=>roleIds.includes(role));return <button key={engineer.id} onClick={()=>toggle(selected,engineer.id,setSelected)} className={`rounded-xl border p-4 text-left ${selected.includes(engineer.id)?"border-emerald-300 bg-emerald-300/10":"border-white/10"}`}><strong>{engineer.profile.name}</strong><div className="mt-2 text-sm text-slate-400">Covers {covered.length} of {required.length} required roles</div><div className="mt-2 flex flex-wrap gap-1">{covered.map(id=><span key={id} className="rounded-full bg-cyan-300/10 px-2 py-1 text-xs text-cyan-100">{roleSkillTaxonomy.find(role=>role.id===id)?.title||id}</span>)}</div></button>})}</div>}</section>
 <section className={`mt-5 rounded-2xl border p-5 ${coverage.complete&&required.length?"border-emerald-300/30 bg-emerald-300/10":"border-amber-300/30 bg-amber-300/10"}`}><h2 className="font-bold">{coverage.complete&&required.length?"Complete role coverage":"Team has uncovered roles"}</h2>{coverage.missingRoleIds.length>0&&<ul className="mt-3 text-sm">{coverage.missingRoleIds.map(id=><li key={id}>• {roleSkillTaxonomy.find(role=>role.id===id)?.title||id}</li>)}</ul>}</section>
 <div className="mt-5 flex flex-wrap items-center justify-end gap-4"><a href="/company/workforce-insights" className="mr-auto text-sm font-bold text-cyan-300">View workforce intelligence</a><span className="text-sm text-slate-400">{status}</span><button onClick={save} disabled={!name.trim()||!required.length||!coverage.complete} className="rounded-xl bg-cyan-300 px-6 py-3 font-bold text-slate-950 disabled:opacity-40">Save covered team</button></div></div></main>;
}
