import React,{useEffect,useState} from "react";
import apiService from "../services/apiService";
import type { TechnicalWorkPack, TechnicalWorkPackInput } from "../types/trust";
import { errorMessage } from "../utils/errorMessage";

const field="mt-1 w-full rounded border border-slate-300 bg-white p-2 text-slate-900";
const lines=(value:string)=>value.split("\n").map(item=>item.trim()).filter(Boolean);

export function TechnicalWorkPackPanel({contractId,roleId,canEdit}:{contractId:string;roleId:string;canEdit:boolean}){
 const [pack,setPack]=useState<TechnicalWorkPack|null>(null),[loading,setLoading]=useState(true),[status,setStatus]=useState("");
 const [form,setForm]=useState({roleId,responsibility:"Deliver the agreed technical responsibility safely and professionally.",scope:"",exclusions:"",prerequisites:"",siteContact:"",escalationContact:"",completionEvidence:"Test results\nClient or site sign-off"});
 useEffect(()=>{apiService.getTechnicalWorkPack(contractId).then((saved)=>{setPack(saved);setForm({roleId:saved.roleId,responsibility:saved.responsibility,scope:saved.scope,exclusions:saved.exclusions.join("\n"),prerequisites:saved.prerequisites.join("\n"),siteContact:saved.siteContact,escalationContact:saved.escalationContact,completionEvidence:saved.completionEvidence.join("\n")});}).catch((error:unknown)=>setStatus(errorMessage(error,"Technical work pack could not be loaded."))).finally(()=>setLoading(false));},[contractId]);
 async function save(){setStatus("Saving…");const input:TechnicalWorkPackInput={...form,exclusions:lines(form.exclusions),prerequisites:lines(form.prerequisites),completionEvidence:lines(form.completionEvidence)};try{const saved=await apiService.saveTechnicalWorkPack(contractId,input);setPack(saved);setStatus(`Work pack version ${saved.version} saved.`);}catch(error:unknown){setStatus(errorMessage(error,"Technical work pack could not be saved."));}}
 if(loading)return <section className="mt-6 rounded-lg border p-5 text-sm text-slate-500">Loading technical work pack…</section>;
 if(!canEdit&&!pack)return <section className="mt-6 rounded-lg border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900">The hiring company has not issued the technical work pack yet.</section>;
 return <section className="mt-6 rounded-lg border border-slate-200 bg-slate-50 p-5"><div className="flex justify-between gap-3"><div><h3 className="font-bold text-slate-900">Technical work pack</h3><p className="mt-1 text-sm text-slate-600">Shared delivery expectations for both contract parties.</p></div>{pack&&<span className="text-sm font-bold text-cyan-700">Version {pack.version}</span>}</div>
 <div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm text-slate-700">Responsibility<textarea disabled={!canEdit} rows={3} value={form.responsibility} onChange={e=>setForm({...form,responsibility:e.target.value})} className={field}/></label><label className="text-sm text-slate-700">Scope and deliverable<textarea disabled={!canEdit} rows={3} value={form.scope} onChange={e=>setForm({...form,scope:e.target.value})} className={field}/></label><label className="text-sm text-slate-700">Exclusions (one per line)<textarea disabled={!canEdit} rows={3} value={form.exclusions} onChange={e=>setForm({...form,exclusions:e.target.value})} className={field}/></label><label className="text-sm text-slate-700">Prerequisites (one per line)<textarea disabled={!canEdit} rows={3} value={form.prerequisites} onChange={e=>setForm({...form,prerequisites:e.target.value})} className={field}/></label><label className="text-sm text-slate-700">Site contact<input disabled={!canEdit} value={form.siteContact} onChange={e=>setForm({...form,siteContact:e.target.value})} className={field}/></label><label className="text-sm text-slate-700">Escalation contact<input disabled={!canEdit} value={form.escalationContact} onChange={e=>setForm({...form,escalationContact:e.target.value})} className={field}/></label><label className="text-sm text-slate-700 md:col-span-2">Completion evidence (one per line)<textarea disabled={!canEdit} rows={3} value={form.completionEvidence} onChange={e=>setForm({...form,completionEvidence:e.target.value})} className={field}/></label></div>
 <div className="mt-4 rounded bg-blue-50 p-3 text-sm text-blue-900">{pack?.paymentNotice||"TechSubbies records scope and delivery only. Job invoicing and payment remain directly between the parties."}</div>{canEdit&&<button onClick={save} className="mt-4 rounded bg-cyan-700 px-4 py-2 font-bold text-white">Save new version</button>}{status&&<p className="mt-2 text-sm text-slate-700">{status}</p>}</section>;
}
