import { Router } from "express";
import { z } from "zod";
import { requireAuth, type AuthedRequest } from "../middleware/auth.js";
import { createAuditEvent, createCompletionValidation, createProjectTeam, deleteTalentPoolEntry, findUserById, getCompanyWorkforceInsights, getContract, getJob, getTechnicalWorkPack, listAuditEvents, listCompletionValidations, listProjectTeams, listTalentPoolEntries, upsertTalentPoolEntry, upsertTechnicalWorkPack } from "../lib/db.js";
import { normaliseRoleId } from "../domain/roleCatalog.js";

export const trustRouter = Router();
const companyRoles = new Set(["Company","Resourcing Company"]);

trustRouter.use((req:AuthedRequest,res,next)=>{res.on('finish',()=>{if(!req.userId||!['POST','PUT','PATCH','DELETE'].includes(req.method)||res.statusCode<200||res.statusCode>=300)return;const parts=req.path.split('/').filter(Boolean);const contractIndex=parts.indexOf('contracts');const contract:any=contractIndex>=0?getContract(parts[contractIndex+1]):undefined;const companyId=contract?.companyId||req.userId;const entityType=parts.includes('talent-pool')?'talent-pool':parts.includes('work-pack')?'work-pack':parts.includes('validation')?'completion-validation':parts.includes('teams')?'project-team':'trust-record';const entityId=contract?.id||parts[parts.length-1]||'new';createAuditEvent(companyId,req.userId,`${req.method.toLowerCase()}.${entityType}`,entityType,entityId,{statusCode:res.statusCode});});next();});

trustRouter.get('/engineers/:engineerId/validations', requireAuth, (req: AuthedRequest,res) => res.json(listCompletionValidations(req.params.engineerId)));
trustRouter.post('/contracts/:contractId/validation', requireAuth, (req: AuthedRequest,res) => {
  const contract:any=getContract(req.params.contractId); if(!contract) return res.status(404).json({error:'Contract not found.'});
  if(contract.companyId!==req.userId!) return res.status(403).json({error:'Only the hiring company can validate delivery.'});
  if(contract.status!=='Completed') return res.status(409).json({error:'Complete the contract before validating delivery.'});
  const parsed=z.object({roleId:z.string().min(1),responsibilityMet:z.boolean(),capabilitiesObserved:z.array(z.string()).max(12),unexpectedSupervisionRequired:z.boolean(),wouldUseAgainForRole:z.boolean(),comments:z.string().max(2000).optional()}).safeParse(req.body);
  if(!parsed.success) return res.status(400).json({error:'Invalid completion validation.'});
  const roleId=normaliseRoleId(parsed.data.roleId);const job:any=getJob(contract.jobId);if(!roleId||roleId!==job?.roleId)return res.status(400).json({error:'Validation must use the canonical role agreed for this contract.'});
  try{return res.status(201).json(createCompletionValidation(contract.id,contract.engineerId,req.userId!,roleId,{...parsed.data,roleId}));}catch{return res.status(409).json({error:'This company has already validated the contract.'});}
});

trustRouter.get('/talent-pool', requireAuth, (req: AuthedRequest,res) => { if(!companyRoles.has(findUserById(req.userId!)?.role||'')) return res.status(403).json({error:'Company account required.'}); return res.json(listTalentPoolEntries(req.userId!)); });
trustRouter.put('/talent-pool/:engineerId', requireAuth, (req: AuthedRequest,res) => { if(!companyRoles.has(findUserById(req.userId!)?.role||'')) return res.status(403).json({error:'Company account required.'}); const parsed=z.object({list:z.enum(['preferred','approved','backup','restricted']),approvedRoleIds:z.array(z.string()).max(30).default([]),approvedClientOrSite:z.string().max(300).optional(),privateNotes:z.string().max(3000).optional()}).safeParse(req.body); if(!parsed.success)return res.status(400).json({error:'Invalid talent-pool entry.'}); if(findUserById(req.params.engineerId)?.role!=='Engineer') return res.status(404).json({error:'Engineer not found.'}); return res.json(upsertTalentPoolEntry(req.userId!,req.params.engineerId,parsed.data.list,parsed.data)); });
trustRouter.delete('/talent-pool/:engineerId', requireAuth, (req: AuthedRequest,res) => { if(!companyRoles.has(findUserById(req.userId!)?.role||'')) return res.status(403).json({error:'Company account required.'}); return res.status(deleteTalentPoolEntry(req.userId!,req.params.engineerId)?204:404).end(); });

const workPackSchema=z.object({roleId:z.string().min(1),responsibility:z.string().min(3).max(1000),scope:z.string().min(20).max(5000),exclusions:z.array(z.string().min(1).max(300)).max(30),prerequisites:z.array(z.string().min(1).max(300)).max(20),siteContact:z.string().min(2).max(300),escalationContact:z.string().min(2).max(300),completionEvidence:z.array(z.string().min(1).max(500)).min(1).max(30)});
trustRouter.get('/contracts/:contractId/work-pack',requireAuth,(req:AuthedRequest,res)=>{const contract:any=getContract(req.params.contractId);if(!contract)return res.status(404).json({error:'Contract not found.'});if(![contract.companyId,contract.engineerId].includes(req.userId!))return res.status(403).json({error:'Not a contract party.'});const pack=getTechnicalWorkPack(contract.id);return pack?res.json(pack):res.status(404).json({error:'Work pack not created.'});});
trustRouter.put('/contracts/:contractId/work-pack',requireAuth,(req:AuthedRequest,res)=>{const contract:any=getContract(req.params.contractId);if(!contract)return res.status(404).json({error:'Contract not found.'});if(contract.companyId!==req.userId!)return res.status(403).json({error:'Only the hiring company can maintain the work pack.'});if(contract.status==='Completed'||contract.status==='Cancelled')return res.status(409).json({error:'The work pack is locked after the contract closes.'});const parsed=workPackSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Invalid technical work pack.',issues:parsed.error.flatten().fieldErrors});const roleId=normaliseRoleId(parsed.data.roleId),job:any=getJob(contract.jobId);if(!roleId||roleId!==job?.roleId)return res.status(400).json({error:'Work pack role must match the canonical contract role.'});return res.json(upsertTechnicalWorkPack(contract.id,req.userId!,{...parsed.data,roleId,paymentNotice:'TechSubbies records scope and delivery only. Job invoicing and payment remain directly between the parties.'}));});

const teamSchema=z.object({name:z.string().trim().min(3).max(200),requiredRoleIds:z.array(z.string().min(1)).min(1).max(20),members:z.array(z.object({engineerId:z.string().min(1),roleIds:z.array(z.string().min(1)).min(1).max(20)})).max(50)});
trustRouter.get('/teams',requireAuth,(req:AuthedRequest,res)=>{if(!companyRoles.has(findUserById(req.userId!)?.role||''))return res.status(403).json({error:'Company account required.'});return res.json(listProjectTeams(req.userId!));});
trustRouter.post('/teams',requireAuth,(req:AuthedRequest,res)=>{if(!companyRoles.has(findUserById(req.userId!)?.role||''))return res.status(403).json({error:'Company account required.'});const parsed=teamSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Invalid project team.'});if(parsed.data.members.some(member=>findUserById(member.engineerId)?.role!=='Engineer'))return res.status(400).json({error:'Every team member must be an engineer.'});const requiredRoleIds=parsed.data.requiredRoleIds.map(normaliseRoleId);const members=parsed.data.members.map(member=>({...member,roleIds:member.roleIds.map(normaliseRoleId)}));if(requiredRoleIds.some(id=>!id)||members.some(member=>member.roleIds.some(id=>!id)))return res.status(400).json({error:'Project teams must use canonical job roles, not skills or job functions.'});return res.status(201).json(createProjectTeam(req.userId!,parsed.data.name,{requiredRoleIds,members}));});
trustRouter.get('/insights',requireAuth,(req:AuthedRequest,res)=>{if(!companyRoles.has(findUserById(req.userId!)?.role||''))return res.status(403).json({error:'Company account required.'});return res.json(getCompanyWorkforceInsights(req.userId!));});
trustRouter.get('/audit',requireAuth,(req:AuthedRequest,res)=>{if(!companyRoles.has(findUserById(req.userId!)?.role||''))return res.status(403).json({error:'Company account required.'});return res.json(listAuditEvents(req.userId!,100));});
